os: linux
language: go
go:
- 1.9

services:
  - docker

before_install:
  - export GOROOT=$(go env GOROOT)

install:
  - go get github.com/golang/dep/cmd/dep
  - go get -u github.com/jstemmer/go-junit-report

script:
  - make update-vendors
  - make tests
