os: linux
sudo: required
language: go
go:
- 1.9

services:
  - docker

before_install:
- export GOROOT=$(go env GOROOT)

install:
- go get -u github.com/jstemmer/go-junit-report

script:
- make test | tee /dev/tty |  go-junit-report > junit-report.xml

after_failure:
  - reports-publisher

after_success:
  - reports-publisher
