[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/buaazp/fasthttprouter"
  branch = "master"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  branch = "master"

[[constraint]]
  name = "github.com/goware/emailx"

[[constraint]]
  name = "github.com/pkg/errors"
